# Generated by Django 5.2.14 on 2026-06-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_add_preprocess_validation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientformfield',
            name='import_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
