import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'app_language';

const translations = {
  fr: {
    languageName: 'Français',
    profile: 'Profil',
    profileTitle: 'Profil utilisateur',
    role: 'Rôle',
    telephone: 'Téléphone',
    changePasswordTitle: 'Modifier votre mot de passe',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le nouveau mot de passe',
    currentPasswordHelper: 'Veuillez entrer votre mot de passe actuel pour confirmer votre identité',
    newPasswordHelper: 'Minimum 8 caractères',
    confirmPasswordHelper: 'Entrez le même mot de passe que ci-dessus',
    submitPassword: 'Modifier le mot de passe',
    cancel: 'Annuler',
    languageSectionTitle: 'Langue de l’interface',
    languageSectionDescription: 'Choisissez la langue d’affichage de la plateforme.',
    languageLabel: 'Langue',
    french: 'Français',
    english: 'Anglais',
    languageBadge: 'Langue active',
    landingTitle: 'Bienvenue dans votre espace santé',
    landingSubtitle: "Ouvrez votre compte sécurisé pour accéder à vos dossiers patients, vos analyses et vos outils de suivi médical.",
    landingCTA: 'Commencer',
    dashboard: 'Tableau de bord',
    patients: 'Patients',
    aiAnalysis: 'Analyse IA',
    monitor: 'Monitor',
    dashboardTitle: 'Tableau de bord',
    dashboardSubtitle: 'Gestion hiérarchisée des utilisateurs, confirmation des opérations sensibles et accès limité aux rôles autorisés.',
    dashboardOpenMonitor: 'Ouvrir le Patient Monitoring Board',
    dashboardVisibleAccounts: 'Comptes visibles',
    dashboardVisibleAccountsDesc: 'Selon votre périmètre d’accès.',
    dashboardActiveAccounts: 'Actifs',
    dashboardActiveAccountsDesc: 'Comptes utilisables immédiatement.',
    dashboardInactiveAccounts: 'Inactifs',
    dashboardInactiveAccountsDesc: 'Comptes suspendus ou revus.',
    dashboardProfessors: 'Professeurs',
    dashboardProfessorsDesc: 'Nombre de professeurs gérés.',
    dashboardResidents: 'Résidents',
    dashboardResidentsDesc: 'Nombre de résidents gérés.',
    dashboardRolesLoaded: 'Rôles chargés',
    dashboardRolesLoadedDesc: 'Profils disponibles dans le système.',
    dashboardSessionActive: 'Session active',
    dashboardConnectedProfile: 'Profil connecté',
    dashboardFullName: 'Nom complet',
    dashboardAccessLimit: 'Accès limité au périmètre autorisé.',
    dashboardDashboardTitle: 'Gestion des comptes',
    dashboardDashboardSubtitle: 'Les super administrateurs et chefs de service gèrent uniquement les Professeurs et Résidents. Saisissez la confirmation pour créer, modifier ou révoquer un compte.',
    dashboardUserManagement: 'Gestion des comptes',
    dashboardUserManagementDesc: 'Les super administrateurs et chefs de service gèrent uniquement les Professeurs et Résidents. Saisissez la confirmation pour créer, modifier ou révoquer un compte.',
    dashboardUserEmail: 'Email',
    dashboardUserPhone: 'Téléphone',
    dashboardUserLastName: 'Nom',
    dashboardUserFirstName: 'Prénom',
    dashboardUserRole: 'Rôle',
    dashboardUserStatus: 'Statut',
    dashboardUserSelectRole: 'Sélectionner',
    dashboardUserActive: 'Actif',
    dashboardUserInactive: 'Inactif',
    dashboardSaveConfirmationPassword: "Mot de passe de validation",
    dashboardCreatePassword: 'Mot de passe du nouveau compte',
    dashboardNewPassword: 'Nouveau mot de passe',
    dashboardCreateButton: 'Créer',
    dashboardUpdateButton: 'Modifier',
    dashboardResetButton: 'Réinitialiser',
    patientsManagementTitle: 'Gestion des données patients',
    patientsListTitle: 'Liste des patients',
    patientsImportHint: "L'import est autorisé, mais la validation reste réservée aux administrateurs et chefs de service",
    patientsReservedHint: 'Réservé aux administrateurs et chefs de service',
    patientsDataStatus: "Statut d'insertion des données",
    patientsImportPendingSince: 'Les données importées sont en attente de validation depuis',
    patientsValidateImport: "Confirmer l'insertion",
    patientsRejectImport: "Annuler l'insertion",
    patientsImportRequiredInfo: "Un chef de service ou un administrateur doit valider l'insertion pour que les données soient prises en compte.",
    patientsImportValidated: 'Insertion validée par',
    patientsImportRejected: 'Insertion annulée par',
    patientsImporting: 'Import...',
    patientsDeleting: 'Suppression...',
    patientsApply: 'Appliquer',
    patientsReset: 'Réinitialiser',
    patientsHideExtraRows: 'Masquer lignes supplémentaires',
    patientsModify: 'Modifier',
    patientsDelete: 'Supprimer',
    patientsNoPatientFound: 'Aucun patient trouvé.',
    patientsSearchName: 'Nom',
    patientsSearchNamePlaceholder: 'Nom du patient',
    patientsSearchId: 'ID patient',
    patientsSearchSex: 'Sexe',
    patientsAgeMin: 'Age min',
    patientsAgeMax: 'Age max',
    patientsSearchAll: 'Tous',
    patientsSearchMale: 'Homme',
    patientsSearchFemale: 'Femme',
    patientsSearchUnknown: 'Inconnu',
    patientsSearchOther: 'Autre',
    patientsImportExcel: 'Importer Excel',
    patientsFilter: 'Filtrer',
    patientsClearImported: 'Vider donnees importees',
    patientsShowAllRows: 'Afficher toutes les lignes',
    patientsSearchPlaceholder: 'Rechercher un utilisateur...',
    patientsSearchResults: 'Résultats',
    patientsNoMatch: 'Aucun patient correspondant.',
    monitorTitle: 'Patient Monitoring Board',
    monitorSubtitle: 'Vue centrée sur un patient unique, combinant informations cliniques, événements du dossier et résultats d’intelligence artificielle.',
    monitorPatientChip: 'Suivi patient',
    monitorClinicalChip: 'Audit clinique',
    monitorSearchSectionTitle: 'Recherche patient',
    monitorSearchTitle: 'Accès direct au dossier',
    monitorSearchPlaceholder: 'Nom, prénom ou identifiant',
    monitorSearchResults: 'Résultats',
    monitorNoMatch: 'Aucun patient correspondant.',
    monitorLoading: 'Chargement des données...',
    monitorSelectPatientTitle: 'Sélectionnez un patient',
    monitorSelectPatientSubtitle: 'Lancez une recherche par identifiant ou nom pour ouvrir le board patient avec son historique clinique et ses analyses IA.',
    monitorPatientFile: 'Dossier patient',
    monitorRiskLabel: 'Risque IA 1 an',
    monitorHistoryTitle: 'Historique des actions',
    monitorDeleteHistory: 'Supprimer de mon historique',
    monitorAITitle: 'Analyse IA',
    monitorModelLabel: 'Modèle',
    monitorScoreLabel: 'Score',
    monitorRiskLevelLabel: 'Niveau de risque',
    monitorInterpretationLabel: 'Interprétation',
    monitorFactorsLabel: 'Facteurs principaux',
    monitorNoPrediction: 'Aucune prédiction IA n’a encore été lancée pour ce patient.',
    monitorOpenAI: 'Ouvrir l’analyse IA',
    monitorNoEvents: 'Aucun événement disponible pour ce patient.',
    monitorPerformedBy: 'Effectué par',
    monitorNoRecommendation: 'Aucune recommandation détaillée disponible.',
    monitorNoFactors: 'Non renseignés.',
    monitorPatientIdAbsent: 'Identifiant absent',
    monitorNoClinicalData: 'Dossier clinique',
    monitorOpenedRecordBy: 'Ouverture du dossier patient par',
    monitorPatientId: 'Identifiant patient',
    monitorFullName: 'Nom complet',
    monitorAge: 'Âge',
    monitorSex: 'Sexe',
    monitorDisease: 'Maladie',
    monitorInclusionStatus: 'Statut inclusion',
    monitorConsent: 'Consentement',
    monitorLastUpdate: 'Dernière mise à jour',
    monitorPatientSaved: 'enregistré dans la plateforme.',
    monitorClinicalDataUpdated: 'Les données cliniques ont été mises à jour.',
    monitorPatientIdMissingShort: 'ID non renseigné',
    monitorActionPatientCreate: 'Création du dossier patient',
    monitorActionPatientUpdate: 'Mise à jour du dossier patient',
    monitorActionPatientDelete: 'Suppression du dossier patient',
    monitorActionPatientConsult: 'Dossier patient consulté',
    monitorActionPatientLatestUpdate: 'Dernière mise à jour',
    monitorActionPrediction: 'Prédiction IA',
    notifications: 'Notifications',
    logout: 'Déconnexion',
    appName: 'AI Néphro',
    appShortName: 'AI Néphro',
    profileUser: 'Profil utilisateur',
    profileTitleSmall: 'Profil utilisateur',
    auditCardTitle: 'Historique d’audit système',
    auditCardDescription: 'Actions enregistrées dans le système et visibles selon le rôle connecté.',
    auditViewerHint: 'Visible pour Super Administrateur et Chef de service',
    auditLoading: 'Chargement de l’historique…',
    auditEmpty: 'Aucune action enregistrée pour le moment.',
    auditError: 'Impossible de charger l’historique d’audit.',
    auditShowDetails: 'Voir détails',
    auditHideEntry: 'Masquer',
    auditDetails: 'Détails',
    auditNoDetails: 'Aucun détail supplémentaire.',
    auditOldValue: 'Ancienne valeur',
    auditNewValue: 'Nouvelle valeur',
    loginTitle: 'Connexion',
    loginSubtitle: 'Connectez-vous pour continuer vers l’espace patient sécurisé.',
    loginButton: 'Connexion',
    emailLabel: 'Email',
    emailPlaceholder: 'admin@hopital.com',
    passwordLabel: 'Mot de passe',
    passwordPlaceholder: '••••••••••••••',
    loginErrorInvalid: 'Identifiants incorrects. Veuillez réessayer.',
    unauthorizedTitle: 'Accès non autorisé',
    unauthorizedMessage: 'Votre rôle ne dispose pas des permissions nécessaires pour afficher cette page.',
    unauthorizedBack: 'Retour au tableau de bord',
    auditActionCreateUser: 'Création d’utilisateur',
    auditActionUpdateUser: 'Modification d’utilisateur',
    auditActionDeleteUser: 'Suppression d’utilisateur',
    auditActionViewPassword: 'Consultation du hash de mot de passe',
    auditActionChangePassword: 'Modification du mot de passe',
    currentPasswordError: 'Veuillez entrer votre mot de passe actuel',
    newPasswordError: 'Veuillez entrer un nouveau mot de passe',
    passwordLengthError: 'Le mot de passe doit contenir au moins 8 caractères',
    passwordMismatchError: 'Les mots de passe ne correspondent pas',
    passwordSameError: 'Le nouveau mot de passe doit être différent du mot de passe actuel',
    passwordSuccess: 'Mot de passe modifié avec succès !',
    passwordGenericError: 'Erreur lors de la modification du mot de passe',
    profileAccountInfo: 'Informations du compte',
    profilePasswordHint: 'Mettez à jour votre accès en toute sécurité.',
    notifTitle: 'Notifications',
    notifPending: 'validation(s) en attente',
    notifNoPending: 'Aucune validation en attente',
    notifAllDone: 'Tout est à jour',
    notifNoPendingAction: 'Aucune action en attente.',
    notifWillBeNotified: "Vous serez notifié dès qu'un import est soumis.",
    notifPreview: 'Aperçu',
    notifReject: 'Refuser',
    notifValidate: 'Valider et intégrer',
    notifValidating: 'Validation...',
    notifRejecting: 'Refus...',
    notifStatusPending: 'Validation en attente',
    notifStatusApproved: 'Validation acceptée',
    notifStatusRejected: 'Validation refusée',
    notifRejectReason: 'Raison du refus :',
    notifNoReason: 'Aucune raison saisie.',
    notifApprovedMsg: 'Validation acceptée',
    notifApprovedBy: 'par',
    notifDataIntegrated: 'Les données ont été intégrées.',
    previewLoading: "Chargement de l'aperçu...",
    previewLoadError: "Impossible de charger l'aperçu.",
    previewAnomalies: 'anomalie(s) détectée(s) — vérifier avant intégration',
    previewFileInfo: 'lignes · Score qualité :',
    previewFooter: 'Aperçu complet du fichier sur',
    previewFooterCols: 'colonne(s).',
    previewClose: 'Fermer',
    previewTabData: 'Données',
    previewTabChanges: 'Modifications',
    previewNoChanges: 'Aucune modification détectée — les données sont identiques à l\'original.',
    previewChangesCount: 'cellule(s) modifiée(s) par le pipeline de prétraitement',
    previewColRow: 'Ligne',
    previewColColumn: 'Colonne',
    previewColOriginal: 'Valeur originale',
    previewColCorrected: 'Valeur corrigée',
    previewOriginalSource: 'Fichier soumis sans correction (source originale).',
    rejectModalTitle: 'Refuser la validation',
    rejectReasonLabel: 'Raison du refus',
    rejectReasonPlaceholder: 'Ex: valeurs incohérentes, colonnes manquantes, corrections à revoir...',
    rejectReasonHint: "Cette raison sera affichée dans les notifications de l'administrateur et du chef de service.",
    rejectCancel: 'Annuler',
    rejectConfirm: 'Confirmer le refus',
    dashboardWelcome: 'Bienvenue',
    dashboardPhoneHelper: 'Numéro du contact principal du compte.',
    dashboardPasswordKeepHint: 'Laisser vide pour conserver le mot de passe actuel.',
    dashboardNewPasswordLabel: 'Nouveau mot de passe',
    dashboardDeleteTitle: 'Confirmer la suppression',
    dashboardDeleteQuestion: 'Voulez-vous vraiment supprimer le compte',
    dashboardDeleteGeneric: 'Voulez-vous vraiment supprimer ce compte ?',
    dashboardDeleteHint: "Si oui, saisis le mot de passe de ton propre compte pour valider l'opération.",
    dashboardDeletePasswordLabel: 'Mot de passe de validation',
    dashboardDeletingButton: 'Suppression...',
    dashboardDeleteButton: 'Supprimer',
    notesTitle: 'Carnet numérique',
    notesOpen: 'Carnet personnel',
    notesMinimize: 'Réduire le carnet',
    notesClose: 'Fermer le carnet',
    notesLoading: 'Chargement...',
    notesPlaceholder: 'Écrivez vos rappels, observations ou idées importantes...',
    notesCharCount: 'caractères',
    notesClear: 'Effacer',
    notesSaving: 'Sauvegarde...',
    notesSaved: 'Sauvegarde',
    notesError: 'Erreur',
    notesReady: 'Prêt',
    notesNoSave: 'Pas encore de sauvegarde',
    notesLastSaved: 'Dernière sauvegarde :',
    notesLoadError: 'Impossible de charger les notes personnelles.',
    notesAutoSaveError: 'Sauvegarde auto indisponible. Vos derniers changements ne sont pas encore enregistrés.',
    modelPatientSearch: 'Rechercher par nom, prénom ou ID...',
    modelColName: 'Nom',
    modelColFirstname: 'Prénom',
    modelColAge: 'Âge',
    modelColAction: 'Action',
    modelAgeUnit: 'ans',
    modelPatientOpen: '✓ Ouvert',
    modelPatientView: 'Voir',
    modelNoPatient: 'Aucun patient trouvé',
    modelPatientRecord: 'Dossier patient',
    modelPatientSelected: 'Sélectionné',
    modelLabelAge: 'Âge',
    modelLabelSex: 'Sexe',
    modelLabelCharlson: 'Score Charlson',
    modelSexMale: 'Masculin',
    modelSexFemale: 'Féminin',
    modelEditHint: 'Modifiez les valeurs pour simuler un scénario',
    modelResetValues: 'Réinitialiser',
    modelBoolYes: 'Oui',
    modelBoolNo: 'Non',
    modelRunPrediction: 'Lancer la prédiction',
    modelRunning: 'Analyse en cours...',
    modelSimulate: 'Simuler',
    modelSimulating: 'Simulation...',
    modelSimResultLabel: '⚗ Résultat simulation',
    modelSimZonePrefix: 'Zone',
    modelSimProba: 'Probabilité',
    modelVarModified: 'var. modifiée',
    modelVarModifiedPlural: 'var. modifiées',
    modelSimOnlyWarning: '⚠ Simulation uniquement — données non sauvegardées',
    modelSelectFirst: 'Sélectionnez d\'abord un patient dans l\'onglet "Patients"',
    modelAnalyzing: 'Analyse des 32 variables cliniques...',
    modelClickToPredict: 'Cliquez sur "Lancer la prédiction" pour analyser ce patient',
    modelDqInsufficient: 'Insuffisante',
    modelDqPartial: 'Partielle',
    modelDqComplete: 'Complète',
    modelRiskRelative: 'Risque rel.',
    modelRiskDeath1y: 'risque de décès à 1 an',
    modelSpectrumLabel: 'Position sur le spectre de risque — cohorte HD-478',
    modelZoneFaibleLabel: 'Faible',
    modelZoneModéréLabel: 'Modéré',
    modelZoneÉlevéLabel: 'Élevé',
    modelRecommendationLabel: 'Recommandation clinique',
    modelFactorsLabel: 'Facteurs déterminants',
    modelRiskBadge: '↑ Risque',
    modelProtectorBadge: '↓ Protecteur',
    modelDataQuality: 'Qualité des données',
    modelVarsUsed: 'Variables utilisées',
    modelDataComplete: 'Données complètes',
    modelShowVars: 'Afficher ▼',
    modelHideVars: 'Masquer ▲',
    modelVarsDetail: 'Détail des 32 variables',
    modelVarsMissing: 'variables manquantes',
    modelImputedKNN: 'imputée(s) (KNN)',
    modelROCAlert: 'Zones issues de la courbe ROC du modèle SVM — à interpréter en complément du jugement clinique.',
    modelAnalyzeAnother: 'Analyser un autre patient',
    modelHeroTitle: 'Modèle AI — Prédiction de Mortalité',
    modelActionLow: 'Suivi standard recommandé',
    modelDetailLow: "Le modèle ne signale pas ce patient comme prioritaire. Continuez le suivi habituel.",
    modelActionModerate: 'Surveillance renforcée',
    modelDetailModerate: "Le modèle signale ce patient. Renforcer la surveillance et réévaluer les facteurs de risque.",
    modelActionHigh: 'Prise en charge prioritaire',
    modelDetailHigh: "Ce patient est dans le groupe à haut risque. Une prise en charge active et urgente est recommandée.",
    modelKpiTotal: 'Total patients',
    modelKpiAvgAge: 'Âge moyen',
    modelKpiAlive: 'Patients en vie',
    modelKpiDeceased: 'Décès enregistrés',
    modelKpiAvgAgeSub: 'Âge moyen',
    modelKpiCohort: 'de la cohorte',
    modelKpiAliveStatus: 'Statut "vivant" enregistré',
    modelKpiNoDeceased: 'Aucun décès enregistré',
    modelKpiCalcOn: 'Calculé sur',
    modelKpiInsufficientData: 'Données insuffisantes',
    modelKpiDatabase: 'Base de données',
    guideTitle: 'Comment utiliser ce module ?',
    guideSubtitle: '4 étapes pour obtenir et explorer un score de risque de mortalité à 1 an',
    guideStep1Title: 'Sélectionner un patient',
    guideStep1Desc: 'Onglet "Patients" → recherchez par nom, prénom ou ID.',
    guideStep2Title: 'Lancer la prédiction',
    guideStep2Desc: 'Cliquez "Lancer la prédiction" — le modèle analyse 32 variables automatiquement.',
    guideStep3Title: 'Lire le résultat',
    guideStep3Desc: 'Onglet "Score" → zone de risque + recommandation clinique + détail des variables.',
    guideStep4Title: 'Simuler une modification',
    guideStep4Desc: "Modifiez une valeur clinique puis cliquez \"Simuler\" pour voir l'impact sur le risque sans sauvegarder.",
    recentActivity: 'Activité récente',
    dashboardNoActivity: 'Aucune activité enregistrée pour le moment.',
    dashboardSuperAdmins: 'Super Admins',
    dashboardChiefService: 'Chefs Service',
    dashboardManagedAccounts: 'Comptes gérés',
    dashboardHide: 'Masquer',
    dashboardShow: 'Afficher',
    roleSuperAdmin: 'Super Administrateur',
    roleChefService: 'Chef de Service',
    roleProfesseur: 'Professeur',
    roleResident: 'Résident',
    tabPretraitement: 'Prétraitement',
    tabGestion: 'Gestion',
    tabAnalyse: 'Analyse',
    modelTabDashboard: 'Tableau de bord',
    modelBaseState: 'État de votre base',
    modelRefresh: 'Actualiser',
    modelToCheck: 'À voir',
    modelCohortAnalysis: 'Analyse de votre cohorte',
    modelZoneFaible: 'Zone Faible',
    modelZoneModerée: 'Zone Modérée',
    modelZoneElevée: 'Zone Élevée',
    modelZoneFaibleThreshold: 'Zone Faible\n(< 10 %)',
    modelZoneModereedThreshold: 'Zone Modérée\n(10–29 %)',
    modelZoneEleveeThreshold: 'Zone Élevée\n(> 29 %)',
    modelZoneFaibleFull: 'Zone Faible (< 10 %)',
    modelZoneModereeFull: 'Zone Modérée (10–29 %)',
    modelZoneEleveeFull: 'Zone Élevée (> 29 %)',
    modelChartMortTitle: 'Que se passe-t-il dans chaque zone ?',
    modelChartMortSubtitle: "Taux de décès réels à 1 an — seuils dérivés par ROC/Youden (cohorte HD-478, n = 478)",
    modelChartRiskTitle: 'Quels facteurs augmentent le risque ?',
    modelChartRiskSubtitle: 'Les 6 variables cliniques les plus déterminantes dans le calcul du score (sur 32 variables analysées)',
    modelChartAlbuminTitle: 'Albumine sérique par zone de risque',
    modelChartAlbuminSubtitle: 'Distribution interquartile (Q1–Q3) — marqueur nutritionnel clé',
    modelChartKMTitle: 'Survie à 12 mois par zone de risque',
    modelChartKMSubtitle: 'Courbes de Kaplan-Meier estimées sur la cohorte HD-478',
    modelChartDevenirTitle: 'Devenir des patients',
    modelChartDevenirSubtitle: 'Statut final enregistré dans le dossier',
    modelChartCharlsonTitle: 'Score de Charlson',
    modelChartCharlsonSubtitle: 'Indice de comorbidités — facteur prédictif clé',
    modelChartDialTitle: 'Durée en dialyse',
    modelChartDialSubtitle: 'Répartition des patients selon la durée de traitement',
    modelOutcomeAlive: 'Vivant',
    modelOutcomeDeceased: 'Décédé',
    modelOutcomeTransplanted: 'Transplanté',
    modelOutcomeLost: 'Perdu de vue',
    modelOutcomeUnknown: 'Non renseigné',
    modelFollowupMonths: 'Mois de suivi',
    modelPatientsLabel: 'patients',
    modelPerfIdentified: 'Patients à risque\nidentifiés',
    modelPerfHealthy: 'Patients sains\nbien classés',
    modelPerfHighDeath: 'Patients classés\nen Zone Élevée\nqui décèdent',
    analysisTitle: "Tableau d'analyse clinique",
    analysisSubtitle: 'Vue professionnelle orientée activité et risques cliniques.',
    analysisKpiTotalPatients: 'Total patients',
    analysisKpiAvgAge: 'Âge moyen',
    analysisKpiCompleteness: 'Complétude',
    analysisKpiTotalCols: 'Colonnes totales',
    analysisKpiDynCols: 'Cols. dynamiques',
    analysisKpiActiveDossiers: 'dossiers actifs',
    analysisKpiMedianAge: 'médiane',
    analysisKpiFieldsFilled: 'des champs remplis',
    analysisKpiPlatformSchema: 'schéma plateforme',
    analysisKpiImported: 'importées',
    analysisMonthlyTitle: 'Évolution mensuelle — début de dialyse',
    analysisNoInclusion: 'Aucune date exploitable pour les inclusions.',
    analysisDistributionTitle: 'Répartition et indicateurs',
    analysisCompTotal: 'Complications totales',
    analysisHighBurden: 'Charge élevée',
    analysisDominantProfile: 'Profil dominant',
    analysisSexDistrib: 'Répartition par sexe',
    analysisAgeSexTitle: "Distribution d'âge par sexe",
    analysisAgeSexSubtitle: 'Histogramme — nombre de patients par tranche d\'âge',
    analysisCompTypesTitle: 'Répartition des types de complications',
    analysisCompTypesSubtitle: 'Nombre de patients par type de complication enregistrée',
    analysisNoComplication: 'Aucune complication renseignée.',
    analysisEtiologyTitle: "Étiologie IRC par statut d'inclusion",
    analysisSexMale: 'Homme',
    analysisSexFemale: 'Femme',
    analysisSexUnknown: 'Inconnu',
  },
  en: {
    languageName: 'English',
    profile: 'Profile',
    profileTitle: 'User profile',
    role: 'Role',
    telephone: 'Phone',
    changePasswordTitle: 'Change your password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    currentPasswordHelper: 'Enter your current password to confirm your identity',
    newPasswordHelper: 'Minimum 8 characters',
    confirmPasswordHelper: 'Enter the same password as above',
    submitPassword: 'Change password',
    cancel: 'Cancel',
    landingTitle: 'Welcome to your health workspace',
    landingSubtitle: 'Open your secure account to access patient records, analyses and monitoring tools.',
    landingCTA: 'Get started',
    languageSectionTitle: 'Interface language',
    languageSectionDescription: 'Choose the display language for the platform.',
    languageLabel: 'Language',
    french: 'French',
    english: 'English',
    languageBadge: 'Active language',
    dashboard: 'Dashboard',
    patients: 'Patients',
    aiAnalysis: 'AI Analysis',
    monitor: 'Monitor',
    dashboardTitle: 'Dashboard',
    dashboardSubtitle: 'Hierarchical management of users, confirmation of sensitive operations, and restricted access by authorized roles.',
    dashboardOpenMonitor: 'Open Patient Monitoring Board',
    patientsManagementTitle: 'Patient data management',
    patientsImportExcel: 'Import Excel',
    patientsFilter: 'Filter',
    patientsClearImported: 'Clear imported data',
    patientsShowAllRows: 'Show all rows',
    patientsSearchPlaceholder: 'Search a user...',
    patientsSearchResults: 'Results',
    patientsNoMatch: 'No matching patient.',
    monitorTitle: 'Patient Monitoring Board',
    monitorSubtitle: 'Patient-centric view combining clinical information, chart events, and artificial intelligence results.',
    monitorPatientChip: 'Patient follow-up',
    monitorClinicalChip: 'Clinical audit',
    monitorSearchSectionTitle: 'Patient search',
    monitorSearchTitle: 'Direct access to the record',
    monitorSearchPlaceholder: 'Name, first name or ID',
    monitorSearchResults: 'Results',
    monitorNoMatch: 'No matching patient.',
    monitorLoading: 'Loading data...',
    monitorSelectPatientTitle: 'Select a patient',
    monitorSelectPatientSubtitle: 'Search by ID or name to open the patient board with clinical history and AI analyses.',
    monitorPatientFile: 'Patient record',
    monitorRiskLabel: '1-year AI risk',
    monitorHistoryTitle: 'Activity history',
    monitorDeleteHistory: 'Remove from my history',
    monitorAITitle: 'AI analysis',
    monitorModelLabel: 'Model',
    monitorScoreLabel: 'Score',
    monitorRiskLevelLabel: 'Risk level',
    monitorInterpretationLabel: 'Interpretation',
    monitorFactorsLabel: 'Key factors',
    monitorNoPrediction: 'No AI prediction has been run for this patient yet.',
    monitorOpenAI: 'Open AI analysis',
    monitorNoEvents: 'No events available for this patient.',
    monitorPerformedBy: 'Performed by',
    monitorNoRecommendation: 'No detailed recommendation available.',
    monitorNoFactors: 'Not provided.',
    monitorPatientIdAbsent: 'ID absent',
    monitorNoClinicalData: 'Clinical record',
    monitorOpenedRecordBy: 'Patient record opened by',
    monitorPatientId: 'Patient ID',
    monitorFullName: 'Full name',
    monitorAge: 'Age',
    monitorSex: 'Sex',
    monitorDisease: 'Disease',
    monitorInclusionStatus: 'Inclusion status',
    monitorConsent: 'Consent',
    monitorLastUpdate: 'Last update',
    monitorPatientSaved: 'saved in the platform.',
    monitorClinicalDataUpdated: 'Clinical data has been updated.',
    monitorPatientIdMissingShort: 'ID not provided',
    monitorActionPatientCreate: 'Patient record creation',
    monitorActionPatientUpdate: 'Patient record update',
    monitorActionPatientDelete: 'Patient record deletion',
    monitorActionPatientConsult: 'Patient record viewed',
    monitorActionPatientLatestUpdate: 'Latest update',
    monitorActionPrediction: 'AI prediction',
    notifications: 'Notifications',
    logout: 'Logout',
    appName: 'AI Nephro',
    appShortName: 'AI Nephro',
    profileUser: 'User profile',
    profileTitleSmall: 'User profile',
    auditCardTitle: 'System audit history',
    auditCardDescription: 'Recorded actions in the system, shown according to the connected role.',
    auditViewerHint: 'Visible to Super Administrator and Service Head',
    auditLoading: 'Loading audit history…',
    auditEmpty: 'No actions recorded yet.',
    auditError: 'Unable to load the audit history.',
    auditShowDetails: 'Show details',
    auditHideEntry: 'Hide',
    auditDetails: 'Details',
    auditNoDetails: 'No additional details available.',
    auditOldValue: 'Old value',
    auditNewValue: 'New value',
    loginTitle: 'Sign in',
    loginSubtitle: 'Sign in to continue to the secure patient area.',
    loginButton: 'Sign in',
    emailLabel: 'Email',
    emailPlaceholder: 'admin@hospital.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••••••••',
    loginErrorInvalid: 'Invalid credentials. Please try again.',
    unauthorizedTitle: 'Unauthorized',
    unauthorizedMessage: 'Your role does not have the required permissions to view this page.',
    unauthorizedBack: 'Back to dashboard',
    auditActionCreateUser: 'User creation',
    auditActionUpdateUser: 'User update',
    auditActionDeleteUser: 'User deletion',
    auditActionViewPassword: 'Password hash viewed',
    auditActionChangePassword: 'Password changed',
    currentPasswordError: 'Please enter your current password',
    newPasswordError: 'Please enter a new password',
    passwordLengthError: 'Password must be at least 8 characters long',
    passwordMismatchError: 'Passwords do not match',
    passwordSameError: 'The new password must be different from the current password',
    passwordSuccess: 'Password changed successfully!',
    passwordGenericError: 'Error while changing password',
    profileAccountInfo: 'Account information',
    profilePasswordHint: 'Update your access securely.',
    notifTitle: 'Notifications',
    notifPending: 'validation(s) pending',
    notifNoPending: 'No pending validation',
    notifAllDone: 'All up to date',
    notifNoPendingAction: 'No pending action.',
    notifWillBeNotified: 'You will be notified when an import is submitted.',
    notifPreview: 'Preview',
    notifReject: 'Reject',
    notifValidate: 'Validate & integrate',
    notifValidating: 'Validating...',
    notifRejecting: 'Rejecting...',
    notifStatusPending: 'Pending validation',
    notifStatusApproved: 'Validation accepted',
    notifStatusRejected: 'Validation rejected',
    notifRejectReason: 'Rejection reason:',
    notifNoReason: 'No reason provided.',
    notifApprovedMsg: 'Validation accepted',
    notifApprovedBy: 'by',
    notifDataIntegrated: 'Data has been integrated.',
    previewLoading: 'Loading preview...',
    previewLoadError: 'Unable to load the preview.',
    previewAnomalies: 'anomaly(ies) detected — verify before integration',
    previewFileInfo: 'rows · Quality score:',
    previewFooter: 'Full preview of file with',
    previewFooterCols: 'column(s).',
    previewClose: 'Close',
    rejectModalTitle: 'Reject validation',
    rejectReasonLabel: 'Rejection reason',
    rejectReasonPlaceholder: 'E.g.: inconsistent values, missing columns, corrections to review...',
    rejectReasonHint: 'This reason will be shown in the notifications of the administrator and service head.',
    rejectCancel: 'Cancel',
    rejectConfirm: 'Confirm rejection',
    previewTabData: 'Data',
    previewTabChanges: 'Changes',
    previewNoChanges: 'No changes detected — data is identical to the original.',
    previewChangesCount: 'cell(s) modified by the preprocessing pipeline',
    previewColRow: 'Row',
    previewColColumn: 'Column',
    previewColOriginal: 'Original value',
    previewColCorrected: 'Corrected value',
    previewOriginalSource: 'File submitted without correction (original source).',
    dashboardVisibleAccounts: 'Visible accounts',
    dashboardVisibleAccountsDesc: 'Based on your access scope.',
    dashboardActiveAccounts: 'Active',
    dashboardActiveAccountsDesc: 'Immediately usable accounts.',
    dashboardInactiveAccounts: 'Inactive',
    dashboardInactiveAccountsDesc: 'Suspended or reviewed accounts.',
    dashboardProfessors: 'Professors',
    dashboardProfessorsDesc: 'Number of professors managed.',
    dashboardResidents: 'Residents',
    dashboardResidentsDesc: 'Number of residents managed.',
    dashboardRolesLoaded: 'Roles loaded',
    dashboardRolesLoadedDesc: 'Profiles available in the system.',
    dashboardSessionActive: 'Active session',
    dashboardConnectedProfile: 'Connected profile',
    dashboardFullName: 'Full name',
    dashboardAccessLimit: 'Access limited to authorized scope.',
    dashboardDashboardTitle: 'Account management',
    dashboardDashboardSubtitle: 'Super administrators and service heads manage only Professors and Residents. Enter the confirmation to create, modify, or revoke an account.',
    dashboardUserManagement: 'Account management',
    dashboardUserManagementDesc: 'Super administrators and service heads manage only Professors and Residents. Enter the confirmation to create, modify, or revoke an account.',
    dashboardUserEmail: 'Email',
    dashboardUserPhone: 'Phone',
    dashboardUserLastName: 'Last name',
    dashboardUserFirstName: 'First name',
    dashboardUserRole: 'Role',
    dashboardUserStatus: 'Status',
    dashboardUserSelectRole: 'Select',
    dashboardUserActive: 'Active',
    dashboardUserInactive: 'Inactive',
    dashboardSaveConfirmationPassword: 'Validation password',
    dashboardCreatePassword: 'New account password',
    dashboardNewPassword: 'New password',
    dashboardCreateButton: 'Create',
    dashboardUpdateButton: 'Update',
    dashboardResetButton: 'Reset',
    patientsListTitle: 'Patient list',
    patientsImportHint: 'Import is permitted, but validation remains reserved for administrators and service heads',
    patientsReservedHint: 'Reserved for administrators and service heads',
    patientsDataStatus: 'Data insertion status',
    patientsImportPendingSince: 'Imported data has been pending validation since',
    patientsValidateImport: 'Confirm insertion',
    patientsRejectImport: 'Cancel insertion',
    patientsImportRequiredInfo: 'A service head or administrator must validate the insertion for the data to be taken into account.',
    patientsImportValidated: 'Insertion validated by',
    patientsImportRejected: 'Insertion rejected by',
    patientsImporting: 'Importing...',
    patientsDeleting: 'Deleting...',
    patientsApply: 'Apply',
    patientsReset: 'Reset',
    patientsHideExtraRows: 'Hide extra rows',
    patientsModify: 'Edit',
    patientsDelete: 'Delete',
    patientsNoPatientFound: 'No patient found.',
    patientsSearchName: 'Last name',
    patientsSearchNamePlaceholder: 'Patient last name',
    patientsSearchId: 'Patient ID',
    patientsSearchSex: 'Sex',
    patientsAgeMin: 'Min age',
    patientsAgeMax: 'Max age',
    patientsSearchAll: 'All',
    patientsSearchMale: 'Male',
    patientsSearchFemale: 'Female',
    patientsSearchUnknown: 'Unknown',
    patientsSearchOther: 'Other',
    recentActivity: 'Recent activity',
    dashboardNoActivity: 'No activity recorded yet.',
    dashboardSuperAdmins: 'Super Admins',
    dashboardChiefService: 'Service Heads',
    dashboardManagedAccounts: 'Managed accounts',
    dashboardHide: 'Hide',
    dashboardShow: 'Show',
    roleSuperAdmin: 'Super Administrator',
    roleChefService: 'Service Head',
    roleProfesseur: 'Professor',
    roleResident: 'Resident',
    tabPretraitement: 'Preprocessing',
    tabGestion: 'Management',
    tabAnalyse: 'Analysis',
    modelTabDashboard: 'Dashboard',
    modelBaseState: 'Your database state',
    modelRefresh: 'Refresh',
    modelToCheck: 'Review',
    modelCohortAnalysis: 'Your cohort analysis',
    modelZoneFaible: 'Low Zone',
    modelZoneModerée: 'Moderate Zone',
    modelZoneElevée: 'High Zone',
    modelZoneFaibleThreshold: 'Low Zone\n(< 10 %)',
    modelZoneModereedThreshold: 'Moderate Zone\n(10–29 %)',
    modelZoneEleveeThreshold: 'High Zone\n(> 29 %)',
    modelZoneFaibleFull: 'Low Zone (< 10 %)',
    modelZoneModereeFull: 'Moderate Zone (10–29 %)',
    modelZoneEleveeFull: 'High Zone (> 29 %)',
    modelChartMortTitle: 'What happens in each zone?',
    modelChartMortSubtitle: 'Actual 1-year mortality rates — thresholds derived by ROC/Youden (HD-478 cohort, n = 478)',
    modelChartRiskTitle: 'Which factors increase the risk?',
    modelChartRiskSubtitle: 'The 6 most decisive clinical variables in the score calculation (out of 32 variables analysed)',
    modelChartAlbuminTitle: 'Serum albumin by risk zone',
    modelChartAlbuminSubtitle: 'Interquartile range (Q1–Q3) — key nutritional marker',
    modelChartKMTitle: '12-month survival by risk zone',
    modelChartKMSubtitle: 'Kaplan-Meier curves estimated on the HD-478 cohort',
    modelChartDevenirTitle: 'Patient outcomes',
    modelChartDevenirSubtitle: 'Final status recorded in the chart',
    modelChartCharlsonTitle: 'Charlson score',
    modelChartCharlsonSubtitle: 'Comorbidity index — key predictive factor',
    modelChartDialTitle: 'Time on dialysis',
    modelChartDialSubtitle: 'Patient distribution by treatment duration',
    modelOutcomeAlive: 'Alive',
    modelOutcomeDeceased: 'Deceased',
    modelOutcomeTransplanted: 'Transplanted',
    modelOutcomeLost: 'Lost to follow-up',
    modelOutcomeUnknown: 'Not recorded',
    modelFollowupMonths: 'Follow-up months',
    modelPatientsLabel: 'patients',
    modelPerfIdentified: 'At-risk patients\nidentified',
    modelPerfHealthy: 'Healthy patients\ncorrectly classified',
    modelPerfHighDeath: 'Patients in\nHigh Zone\nwho die',
    dashboardWelcome: 'Welcome',
    dashboardPhoneHelper: 'Primary contact number for the account.',
    dashboardPasswordKeepHint: 'Leave blank to keep the current password.',
    dashboardNewPasswordLabel: 'New password',
    dashboardDeleteTitle: 'Confirm deletion',
    dashboardDeleteQuestion: 'Do you really want to delete the account',
    dashboardDeleteGeneric: 'Do you really want to delete this account?',
    dashboardDeleteHint: 'If yes, enter your own account password to confirm the operation.',
    dashboardDeletePasswordLabel: 'Validation password',
    dashboardDeletingButton: 'Deleting...',
    dashboardDeleteButton: 'Delete',
    notesTitle: 'Digital notebook',
    notesOpen: 'Personal notebook',
    notesMinimize: 'Minimize notebook',
    notesClose: 'Close notebook',
    notesLoading: 'Loading...',
    notesPlaceholder: 'Write your reminders, observations or important ideas...',
    notesCharCount: 'characters',
    notesClear: 'Clear',
    notesSaving: 'Saving...',
    notesSaved: 'Saved',
    notesError: 'Error',
    notesReady: 'Ready',
    notesNoSave: 'No save yet',
    notesLastSaved: 'Last saved:',
    notesLoadError: 'Unable to load personal notes.',
    notesAutoSaveError: 'Auto-save unavailable. Your latest changes are not yet saved.',
    modelPatientSearch: 'Search by last name, first name or ID...',
    modelColName: 'Last name',
    modelColFirstname: 'First name',
    modelColAge: 'Age',
    modelColAction: 'Action',
    modelAgeUnit: 'yr',
    modelPatientOpen: '✓ Opened',
    modelPatientView: 'View',
    modelNoPatient: 'No patient found',
    modelPatientRecord: 'Patient record',
    modelPatientSelected: 'Selected',
    modelLabelAge: 'Age',
    modelLabelSex: 'Sex',
    modelLabelCharlson: 'Charlson score',
    modelSexMale: 'Male',
    modelSexFemale: 'Female',
    modelEditHint: 'Modify values to simulate a scenario',
    modelResetValues: 'Reset',
    modelBoolYes: 'Yes',
    modelBoolNo: 'No',
    modelRunPrediction: 'Run prediction',
    modelRunning: 'Analysis in progress...',
    modelSimulate: 'Simulate',
    modelSimulating: 'Simulating...',
    modelSimResultLabel: '⚗ Simulation result',
    modelSimZonePrefix: 'Zone',
    modelSimProba: 'Probability',
    modelVarModified: 'var. modified',
    modelVarModifiedPlural: 'vars. modified',
    modelSimOnlyWarning: '⚠ Simulation only — data not saved',
    modelSelectFirst: 'First select a patient in the "Patients" tab',
    modelAnalyzing: 'Analysing 32 clinical variables...',
    modelClickToPredict: 'Click "Run prediction" to analyse this patient',
    modelDqInsufficient: 'Insufficient',
    modelDqPartial: 'Partial',
    modelDqComplete: 'Complete',
    modelRiskRelative: 'Rel. risk',
    modelRiskDeath1y: '1-year death risk',
    modelSpectrumLabel: 'Position on the risk spectrum — HD-478 cohort',
    modelZoneFaibleLabel: 'Low',
    modelZoneModéréLabel: 'Moderate',
    modelZoneÉlevéLabel: 'High',
    modelRecommendationLabel: 'Clinical recommendation',
    modelFactorsLabel: 'Determining factors',
    modelRiskBadge: '↑ Risk',
    modelProtectorBadge: '↓ Protective',
    modelDataQuality: 'Data quality',
    modelVarsUsed: 'Variables used',
    modelDataComplete: 'Complete data',
    modelShowVars: 'Show ▼',
    modelHideVars: 'Hide ▲',
    modelVarsDetail: 'Detail of 32 variables',
    modelVarsMissing: 'missing variables',
    modelImputedKNN: 'imputed (KNN)',
    modelROCAlert: 'Zones derived from the model ROC curve — to be interpreted alongside clinical judgement.',
    modelAnalyzeAnother: 'Analyse another patient',
    modelHeroTitle: 'AI Model — Mortality Prediction',
    modelActionLow: 'Standard follow-up recommended',
    modelDetailLow: 'The model does not flag this patient as a priority. Continue standard monitoring.',
    modelActionModerate: 'Reinforced monitoring',
    modelDetailModerate: 'The model flags this patient. Strengthen monitoring and reassess risk factors.',
    modelActionHigh: 'Priority care',
    modelDetailHigh: 'This patient is in the high-risk group. Active and urgent management is recommended.',
    modelKpiTotal: 'Total patients',
    modelKpiAvgAge: 'Average age',
    modelKpiAlive: 'Living patients',
    modelKpiDeceased: 'Recorded deaths',
    modelKpiAvgAgeSub: 'Average age',
    modelKpiCohort: 'of the cohort',
    modelKpiAliveStatus: '"Alive" status recorded',
    modelKpiNoDeceased: 'No recorded deaths',
    modelKpiCalcOn: 'Calculated on',
    modelKpiInsufficientData: 'Insufficient data',
    modelKpiDatabase: 'Database',
    guideTitle: 'How to use this module?',
    guideSubtitle: '4 steps to obtain and explore a 1-year mortality risk score',
    guideStep1Title: 'Select a patient',
    guideStep1Desc: '"Patients" tab → search by last name, first name or ID.',
    guideStep2Title: 'Run prediction',
    guideStep2Desc: 'Click "Run prediction" — the model analyses 32 variables automatically.',
    guideStep3Title: 'Read the result',
    guideStep3Desc: '"Score" tab → risk zone + clinical recommendation + variable details.',
    guideStep4Title: 'Simulate a change',
    guideStep4Desc: 'Modify a clinical value then click "Simulate" to see the impact on risk without saving.',
    tabModelAI: 'AI Model',
    analysisTitle: 'Clinical analysis dashboard',
    analysisSubtitle: 'Professional view focused on activity and clinical risks.',
    analysisKpiTotalPatients: 'Total patients',
    analysisKpiAvgAge: 'Average age',
    analysisKpiCompleteness: 'Completeness',
    analysisKpiTotalCols: 'Total columns',
    analysisKpiDynCols: 'Dynamic cols.',
    analysisKpiActiveDossiers: 'active records',
    analysisKpiMedianAge: 'median',
    analysisKpiFieldsFilled: 'of fields filled',
    analysisKpiPlatformSchema: 'platform schema',
    analysisKpiImported: 'imported',
    analysisMonthlyTitle: 'Monthly evolution — dialysis start',
    analysisNoInclusion: 'No usable date for inclusions.',
    analysisDistributionTitle: 'Distribution and indicators',
    analysisCompTotal: 'Total complications',
    analysisHighBurden: 'High burden',
    analysisDominantProfile: 'Dominant profile',
    analysisSexDistrib: 'Sex distribution',
    analysisAgeSexTitle: 'Age distribution by sex',
    analysisAgeSexSubtitle: 'Histogram — patients per age group',
    analysisCompTypesTitle: 'Complication types',
    analysisCompTypesSubtitle: 'Patients per recorded complication type',
    analysisNoComplication: 'No complication recorded.',
    analysisEtiologyTitle: 'CKD etiology by inclusion status',
    analysisSexMale: 'Male',
    analysisSexFemale: 'Female',
    analysisSexUnknown: 'Unknown',
  },
};

const LanguageContext = createContext({
  language: 'fr',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === 'en' ? 'en' : 'fr';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (nextLanguage) => {
    setLanguageState(nextLanguage === 'en' ? 'en' : 'fr');
  };

  const toggleLanguage = () => {
    setLanguageState((current) => (current === 'fr' ? 'en' : 'fr'));
  };

  const t = useMemo(() => {
    return (key) => translations[language]?.[key] || translations.fr[key] || key;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, toggleLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
